### Create a normal comment

POST {{baseUrl}}/api/comments
Accept: */*
Cache-Control: no-cache
User-Agent: Test-agent/1234
Content-Type: application/json

{
	"postId": "1234",
	"author": "panta",
	"text": "Some text"
}

### Create a reply

POST {{baseUrl}}/api/comments
Accept: */*
Cache-Control: no-cache
User-Agent: Test-agent/1234
Content-Type: application/json

{
	"postId": "1234",
	"author": "panta",
	"text": "Some some reply",
	"replyToId": "5cc4afacb248f521f0ff5629"
}

###
